# Generated by Django 3.1.4 on 2021-05-10 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_com_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='downvoting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='upvoting', to=settings.AUTH_USER_MODEL),
        ),
    ]
