# Generated by Django 3.1.4 on 2021-05-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210517_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='ordercancelled',
            field=models.BooleanField(default=False),
        ),
    ]
